##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - aptitude
    - autoconf
    - clang-tools
    - expect #required for unbuffer
    - gettext
    - pkg-config
    - librsvg2-bin
    - librsvg2-common
    - make

before_scripts:
  - ./debrepo-install 'libctk-3-bin'

build_scripts:
  - ./make-scanbuild
